export const TABLE_TYPE = {
    date: 'date',
    dateUtc: 'dateUtc',
    detailButton: 'detail-button',
    checker: 'checkContent',
    revokeButton: 'revoke-button',
    assignButton: 'assign-button',
    image: 'image',
    fullImage: 'fullImage',
    url: 'url',
    status: 'status',
    uploadButton: 'upload-button',
    orderButton: 'order-button',
    deleteButton: 'delete-button',
  };